import { isCurrentUserBlocked } from '@/actions/relations';
import MainLayout from '@/components/layout/MainLayout/MainLayout';
import ProfileCap from '@/components/layout/ProfileLayout/ProfileCap/ProfileCap';
import ProfileLayout from '@/components/layout/ProfileLayout/ProfileLayout';
import ProfNav from '@/components/layout/ProfileLayout/ProfNav/ProfNav';
import { redirect } from 'next/navigation';
// import { Metadata } from 'next';
import React, { Suspense } from 'react';
import { toast } from 'react-toastify';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { nickname: string };
}>) {
  const res = await isCurrentUserBlocked(params.nickname);
  if (res.ok && res.data?._id) {
    redirect('/home?blocked=true&reason=user_blocked');
  }
  return <ProfileLayout>{children}</ProfileLayout>;
}
