import MainLayout from '@/components/layout/MainLayout/MainLayout';
import ProfileCap from '@/components/shared/ProfileCap/ProfileCap';
import ProfNav from '@/components/shared/ProfNav/ProfNav';
// import { Metadata } from 'next';
import React from 'react';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ProfileCap />
      <ProfNav />
      {/* <div style={{ backgroundColor: '#EDF1F5' }}>{children}</div> */}
      {children}
    </>
  );
}
